name: Install/upgrade PR Instance
on:
  pull_request:
    branches:
      - develop
    paths:
      - 'services/**'
    types:
      - opened
      - synchronize

jobs:

  build_api:
    name: 'Build Traction API'
    runs-on: ubuntu-20.04
    steps:      
      - uses: actions/checkout@v2        
      - name: Build service
        uses: ./.github/actions/build_service
        id: builder
        with:
          context: './services/traction'
          image_name: ${{ github.repository_owner}}/traction-api
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}          
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  deploy:
    name: Deploy PR
    environment: tools
    runs-on: ubuntu-20.04
    needs: 
      - build_api
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    
    steps:  
      - uses: actions/checkout@v2  

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      
      - name: Run PR Helm 
        run: |
          yq eval '.global.fullnameOverride = "pr-${{ github.event.number }}-traction"' -i ./charts/traction/values-pr.yaml
          yq eval '.postgresql.fullnameOverride = "pr-${{ github.event.number }}-traction"' -i ./charts/traction/values-pr.yaml
          yq eval '.traction_api.image.tag = "${{ needs.build_api.outputs.image_tag }}"' -i ./charts/traction/values-pr.yaml
          yq eval '.traction_api.image.version = "${{ needs.build_api.outputs.image_version }}"' -i ./charts/traction/values-pr.yaml
          yq eval '.traction_api.image.buildtime = "${{ needs.build_api.outputs.buildtime }}"' -i ./charts/traction/values-pr.yaml
          helm upgrade -f ./charts/traction/values.yaml -f ./charts/traction/values-pr.yaml pr-${{ github.event.number }}-traction ./charts/traction --install --wait
